when:
  - event: [push, manual]
    branch: main
    status: [success, failure]

labels:
  backend: local

depends_on: [pts-build-compile]

steps:
  - name: delete-vm
    image: bash
    environment:
      WOODPECKER_API_TOKEN:
        from_secret: woodpecker_api_token
    commands:
      - scripts/woodpecker/pts-cleanup.sh

  - name: notify
    image: bash
    environment:
      SLACK_WEBHOOK_URL:
        from_secret: slack_webhook_url
    commands:
      - scripts/woodpecker/pts-notify.sh
    when:
      - status: [success, failure]
    depends_on: [delete-vm]
